### ISSUE TITLE
CLI usability improvements

### ISSUE THREAD

**Issue by nicoloboschi** [LangStream/langstream#110]
```[tasklist]
### Tasks
- [ ] Generate autocompletion
- [ ] Add enum values in the help
- [ ] Introduce profile
- [ ] Save a common configuration in the user home (~/.sgai/config)
- [ ] Create brew distribution
```

**Comment by nicoloboschi** [comment]
Closed in favor of #237
